model:
  name: "multiexit_unet"
  filters: [64, 128, 256, 512, 512, 512, 512, 512, 512, 512, 512, 512]
  strides: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2 ,2]
  num_res_units: 2
  spatial_dims: 1
  in_channels: 2
  out_channels: 2
  exit_out_channels: 2
  exit_at_stages: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  exit_weights: [2048, 1024, 512, 256, 128, 64, 32, 16, 8, 4, 2, 1] # from bottleneck-side ----> output-side
  bottleneck:
    type: "resnet" # mobilenetv2 resnet 
    expansion: 2
  loss:
    softness: 10
    limit_db: -50
    per_sample: True
    
dataset:
  batch_size: 64
  batch_size_val: 1
  win_len: 40960
  num_workers: 5
  fold_idx: 0
  sinr_db_min: -30
  sinr_db_max: 0
  val_ratio: 0
  split_names:
    - train_indices
    - test_indices
  sps: 16
  span: 8
  beta: 0.5
  use_balanced_sampler: True
  folds_yaml_path: dataset/folds.yaml
  data_pt_path: dataset/combined_signals.pt

training:
  steps: 100000
  lr: 0.0001
  weight_decay: 0.01
  mixed_precision: True
  log_freq: 10
  model_saving_freq: 100


seed: 42
project_name: RegretLess
